const express = require("express");
const authMiddleware = require("../middlewares/auth.middleware");
const interviewRouter = express.Router();
const interviewController = require("../controllers/interview.controller");
const upload = require("../middlewares/file.middleware");

/**
 * @router POST /api/interview
 * @description: Generate new interview reports on the basis of user self description resume pdf and job description
 * @access: Private
 *
 */

interviewRouter.post(
  "/",
  authMiddleware.authUser,
  upload.single("resume"),
  interviewController.generateInterviewReportController,
);

/**
 * @router GET /api/interview/report/:interviewId
 * @description:Get Interview Report by Id
 * @access: Private
 */
interviewRouter.get(
  "/report/:interviewId",
  authMiddleware.authUser,
  interviewController.getInterviewReportByIdController,
);

/**
 * @router GET /api/interview
 * @description:Get All Interview reports of logged in user
 * @access: Private
 */

interviewRouter.get(
  "/",
  authMiddleware.authUser,
  interviewController.getAllInterviewReportsController,
);

/**
 * @router DELETE /api/interview/:interviewId
 * @description: Delete Interview Report
 * @access: Private
 */

interviewRouter.delete(
  "/:interviewId",
  authMiddleware.authUser,
  interviewController.deleteInterviewReportController,
);

/**
 * @router POST /api/interview/resume/pdf
 * @description:generate resume pdf on the basis of user self description,resume content and job description
 * @access: Private
 */

// interviewRouter.post(
//   "/resume/pdf/:interviewReportId",
//   authMiddleware.authUser,
//   interviewController.generateResumePdfController,
// );


/**
 * @router POST /api/interview/mockInterview/start/interviewReportId
 * @description: Generate Mock Interview Report on the basic of user's self description, resume content and job description, skillGaps
 * @access: Private
 */

interviewRouter.post(
  "/mock-interview/start/:interviewReportId",
  authMiddleware.authUser,
  interviewController.generateMockInterviewController,
);

/**
 * @router GET /api/interview/mockInterview/:mockInterviewId
 * @description: Get mockInterview that are generated by Ai
 * @access: Private
 */

interviewRouter.get(
  "/mock-interview/:mockInterviewId",
  authMiddleware.authUser,
  interviewController.getMockInterviewController,
);

/**
 * @router POST /api/interview/mockInterview/answer
 * @description: save the answer to the mock interview question
 * @access: Private
 */

interviewRouter.post(
  "/mock-interview/answer/",
  authMiddleware.authUser,
  interviewController.saveMockInterviewAnswerController,
);

/**
 * @router Get /api/interview/mockInterview/
 * @description: save the answer to the mock interview question
 * @access: Private
 */

interviewRouter.post(
  "/mock-interview/answer/",
  authMiddleware.authUser,
  interviewController.saveMockInterviewAnswerController,
);

/**
 * @router POST /api/interview/mockInterview/finish/mockinterviewId
 * @description: user Finish The mock interview and get the final mockInterview report generated by Ai on the basis of his answers
 * @access: Private
 */

interviewRouter.post(
  "/mock-interview/finish/:mockInterviewId",
  authMiddleware.authUser,
  interviewController.finishMockInterviewController,
);

/**
 * @router POST /api/interview/mockInterview/finish/mockinterviewId
 * @description: user Finish The mock interview and get the final mockInterview report generated by Ai on the basis of his answers
 * @access: Private
 */

interviewRouter.post(
  "/mock-interview/finish/:mockInterviewId",
  authMiddleware.authUser,
  interviewController.finishMockInterviewController,
);

/**
 * @router GET /api/interview/mockInterview/report/mockinterviewId
 * @description: Get MockInterview Interview Report
 * @access: Private
 */

interviewRouter.get(
  "/mock-interview/report/:mockInterviewId",
  authMiddleware.authUser,
  interviewController.getMockInterviewReportController,
);

/**
 * @router GET /api/interview/mockInterview/report/mockinterviewId
 * @description: Get All MockInterview  Reports
 * @access: Private
 */

interviewRouter.get(
  "/mock-interview/",
  authMiddleware.authUser,
  interviewController.getAllMockInterviewReportsController,
);

/**
 * @router DELETE /api/interview/mockInterview/mockinterviewId
 * @description: Delete MockInterview Report
 * @access: Private
 */

interviewRouter.delete(
  "/mock-interview/report/:mockInterviewId",
  authMiddleware.authUser,
  interviewController.deleteMockInterviewReportController,
);

module.exports = interviewRouter;
